# Generated by Django 4.2.7 on 2024-01-16 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsletter_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер клиента'),
        ),
        migrations.AddField(
            model_name='message',
            name='newsletter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newsletter_app.newsletter', verbose_name='Рассылка'),
        ),
        migrations.AddField(
            model_name='logs',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter_app.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='logs',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter_app.newsletter', verbose_name='Рассылка'),
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Менеджер клиента'),
        ),
    ]
