# Generated by Django 4.2.7 on 2024-01-16 07:48

from django.db import migrations, models
import newsletter_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст блога')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('views', models.IntegerField(blank=True, null=True, verbose_name='Количество просмотров')),
                ('published_date', models.DateField(default=newsletter_app.models.get_date_now, verbose_name='Дата публикации')),
            ],
        ),
    ]
